version: '3.8'

services:

    php:
        build:
            dockerfile: docker-conf/php-dockerfile
            context: .
        volumes:
            - ./app:/var/www/html/app
            - ./config:/var/www/html/config
            - type: bind
              source: ./www/index.php
              target: /var/www/html/www/index.php
            - type: bind
              source: ./docker-conf/php/php.ini
              target: /usr/local/etc/php/conf.d/php.ini
            - type: tmpfs
              target: /var/www/html/temp
            - type: tmpfs
              target: /var/www/html/log
        environment:
            - DEBUG=${DEBUG}

    nginx:
        image: nginx:latest
        ports:
            - ${PORT}:80
        links:
            - 'php'
        volumes:
            - ./docker-conf/nginx:/etc/nginx/conf.d
            - ./www:/var/www/html/www
        depends_on:
            - php